version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: tools/ubuntu/setup.dev.sh
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr ..
      - run: make -j4
      - run: ctest -V
      - run: make install
