version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: tools/circleci/compile.sh
      - setup_remote_docker:
        docker_layer_caching: true

